spring:
  application:
    name: sp2
  profiles:
    active: "@spring.profiles.active@"

management:
  endpoint:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO
